name: Build EXE

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Build EXE
        run: pyinstaller main.py --onefile --name bpsr-fishing

      - name: Upload EXE artifact
        uses: actions/upload-artifact@v3
        with:
          name: bpsr-fishing-exe
          path: dist/bpsr-fishing.exe
